apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nightscout
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Release.Name }}-nightscout
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nightscout
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ $.Release.Name }}-nightscout
      terminationGracePeriodSeconds: 5
      containers:
        - name: nightscout
          {{- with .Values.image }}
          image: "{{ .registry }}/{{ .repository }}:{{ .tag }}"
          {{- end }}
          ports:
            - containerPort: 1337
              name: http
          env:
            - name: INSECURE_USE_HTTP
              value: "false"
            - name: TZ
              value: {{ .Values.timezone }}
            - name: AUTH_DEFAULT_ROLES
              value: denied
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecret.name }}
                  key: {{ .Values.apiSecret.key }}
            - name: BASE_URL
              value: "https://{{ .Values.externalHost }}"
            - name: DISPLAY_UNITS
              value: {{ .Values.displayUnits }}
            {{- with .Values.mongo }}
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .credentialSecret.name }}
                  key: {{ .credentialSecret.usernameKey }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .credentialSecret.name }}
                  key: {{ .credentialSecret.passwordKey }}
            - name: MONGODB_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@{{ .host }}:{{ .port }}/{{ .database }}?authMechanism=PLAIN"
            {{- end }}
            {{- range $key, $value := .Values.browserDefaults }}
            - name: {{ $key | snakecase | upper }}
              value: {{ $value | quote }}
            {{- end }}
