---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name}}-github-pull-secret
spec:
  secretStoreRef:
    name: doppler-born
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-github-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{{ `{"auths":{"ghcr.io":{"auth":"{{ printf "%s:%s" .username .token | b64enc }}"}}}` }}'
  data:
    - remoteRef:
        key: GITHUB_PACKAGE_TOKEN
      secretKey: token
    - remoteRef:
        key: GITHUB_PACKAGE_USERNAME
      secretKey: username
