---
{{- with .Values.ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ $.Release.Name }}-cert-tls
  rules:
    - host: {{ .host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-nightscout
                port:
                  name: http
            pathType: Prefix
            path: "/"
{{- end }}
{{- end }}
