apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-nightscout
  ports:
    - port: 80
      name: http
      targetPort: http
